include ':android', ':crypto', ':preparation', ':environment:discovery', ':config'

project(':android').projectDir = file('modules/android')
project(':crypto').projectDir = file('modules/crypto')
project(':preparation').projectDir = file('modules/preparation')
project(':environment').projectDir = file('modules/environment')
project(':environment:discovery').projectDir = file('modules/environment/discovery')
project(':config').projectDir = file('modules/config')

rootProject.name = "cryptobenchmark"
