apply plugin: 'java-library'
apply plugin: 'org.jetbrains.kotlin.jvm'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

compileKotlin {
    kotlinOptions.jvmTarget = '1.8'
}

dependencies {
    implementation 'org.yaml:snakeyaml:2.3'
    testImplementation 'junit:junit:4.13.2'
}
